[project]
name = "call"
version = "0.1.0"
description = "Call me maybe project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.3.0",
    "flake8-docstrings>=1.7.0",
    "llm-sdk",
    "mypy>=2.3.1",
    "pydantic>=2.13.4",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }

[tool.mypy]
mypy_path = ["llm_sdk"]
